[package]
name = "dicom"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
dicom-object = "0.7"
dicom-dictionary-std = "0.7.0"
dicom-core = "0.7.0"
wasm-bindgen = "0.2.80"